Feature/test-create
moleculerjs/moleculer-cli pull request #42
Opened 2021-03-29 22:50 UTC by devalexandre

test implementation proposal.

```
npx jest test/**/*.spec.js --detectOpenHandles --forceExit
```

![](https://i.ibb.co/QvBY1xy/Captura-de-Tela-2021-03-29-a-s-19-49-04.png)

2021-03-31 07:41 UTC, icebob requested changes

2021-03-31 07:41 UTC, icebob commented on test/e2e/create/create.spec.js
> +		fs.unlinkSync(_path);
Please check the content of the file, not just the existing.

2021-03-31 07:41 UTC, icebob commented on test/e2e/create/create.spec.js
> +		fs.unlinkSync(_path);
Same here

2021-03-31 22:23 UTC, devalexandre reviewed
checked files content

2021-04-08 13:36 UTC, icebob requested changes

2021-04-08 13:36 UTC, icebob commented on test/e2e/create/create.spec.js
> +		expect(fs.existsSync(_path)).toBeTruthy();
Would be better to change the order of `expect`. IF the content is same, not relevant to check the existing. But if the file is not exist, no need to check the content.

2021-04-08 19:04 UTC, icebob commented
The `npm test` doesn't work.

![image](https://user-images.githubusercontent.com/306521/114082374-f0b3a000-98ad-11eb-91bf-d803e6c265e7.png)

2021-04-10 15:27 UTC, devalexandre reviewed
![](https://i.ibb.co/nfCW4Ms/Captura-de-Tela-2021-04-10-a-s-12-26-23.png)

2021-04-11 12:50 UTC, icebob approved these changes
Thanks.

2021-04-11 12:50 UTC, merged